### ISSUE TITLE
Bug certificate retrieve   1865027

### ISSUE THREAD

**Issue by gnarco** [Arianee/arianeeJS#116] opened 2019-11-13 15:40 UTC
Cert : 1865027
Url : https://arian.ee/customCert?name=My custom certificate

Space are replaced by %20 in browser

Perhaps, it's not handled by arianeeJs

**Comment by stefdelec** [comment] 2019-11-15 13:59
I can't reproduce the issue. I think it was resolved by the fallback rpc issue.
https://github.com/Arianee/arianeeJS/pull/117

**Closed** 2019-12-03 16:25 UTC
Labels: BUG - P2
